### ISSUE TITLE
Casting to multiple devices will stop at the first offline device in the list

### ISSUE THREAD

**Issue by zeroZshadow** [b0mbays/continuously_casting_dashboards#103]
If I have multiple devices in the list, and one of them is offline, it will not start casting to any device AFTER the offline machine.

Example: 
```
continuously_casting_dashboards:
  logging_level: warning
  cast_delay: 30
  switch_entity_id: "input_boolean.casting"
  devices:
    "192.168.0.5":
      - dashboard_url: "http://192.168.0.2:8123/dashboard-test/0?kiosk"
    "192.168.0.6":
      - dashboard_url: "http://192.168.0.2:8123/dashboard-test/0?kiosk"
```

If `192.168.0.5` is offline, no cast to `192.168.0.6` will start.
if `192.168.0.5` is online, a cast to both it at `192.168.0.6` will work.

Expected:

It should skip the offline device and still cast to the other devices on the list
