### ISSUE TITLE
Not recasting after planned break

### ISSUE THREAD

**Issue by thewookiewon** [b0mbays/continuously_casting_dashboards#104]
I have a scheduled break during the day from 2800-2100GMT and so far two days in a row out fails to cast after 2100.

If I restart HA it'll cast immediately 

`logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
end_time: "00:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
switch_entity_id: "input_boolean.ccd_cast"
devices:
  "REDACTED IP": #Required: Display name or IP address of your device. Find this on the actual device's settings or inside the Google Home app.
    - dashboard_url: "HTTP:// REDACTED IP:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "07:00" #Optional: Set the start time for this device
      end_time: "18:00" #Optional: Set the end time for this device
    - dashboard_url: "HTTP:// REDACTED IP:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "21:00" #Optional: Set the start time for this device
      end_time: "22:45" #Optional: Set the end time for this device`

**Comment by thewookiewon** [comment]
Status.json
```
{
  "total_devices": 1,
  "connected_devices": 0,
  "disconnected_devices": 1,
  "media_playing_devices": 0,
  "other_content_devices": 0,
  "last_updated": "2025-03-23T21:43:11.951548",
  "devices": {
    "192.168.251.86": {
      "ip": "192.168.251.86",
      "status": "disconnected",
      "last_checked": "2025-03-23T21:00:45.719337",
      "reconnect_attempts": 0
    }
  }
}
```

**Comment by b0mbays** [comment]
I think the issue here is the integration is confused about the global end time being midnight, could you set that to either 00.01 or 23.59? That should fix this issue 👍

**Comment by thewookiewon** [comment]
I've set it to the default of 0100, found this in the logging with debug on.

`2025-03-23 22:33:14.628 DEBUG (MainThread) [custom_components.continuously_casting_dashboards.device] Device at REDACTED IP is idle (only volume info returned)
2025-03-23 22:33:14.679 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.13/json/__init__.py:180: RuntimeWarning: coroutine '_make_delegate_method.<locals>.method' was never awaited
  fp.write(chunk)`

**Comment by b0mbays** [comment]
So, that device is suppose to be connecting currently but it's not? (well it should be before 22.45?)

**Comment by thewookiewon** [comment]
Yes that's correct, for whatever reason the logging suggest it's outside the time permitted when it was 19 minutes left. 

2025-03-23 22:26:15.931 INFO (MainThread) [custom_components.continuously_casting_dashboards.monitoring] Outside casting time window for 192.168.251.86, skipping reconnect

**Comment by b0mbays** [comment]
Could you re-post your configuration but retain the formatting?

**Comment by thewookiewon** [comment]
logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
switch_entity_id: "input_boolean.ccd_cast"
devices:
  "REDACTED IP": #Required: Display name or IP address of your device. Find this on the actual device's settings or inside the Google Home app.
    - dashboard_url: "http://REDACTED:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "07:00" #Optional: Set the start time for this device
      end_time: "18:00" #Optional: Set the end time for this device
    - dashboard_url: "http://REDACTED:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "21:00" #Optional: Set the start time for this device
      end_time: "22:45" #Optional: Set the end time for this device

**Comment by b0mbays** [comment]
That is strange. And that was after a restart _after_ changing your configuration file?

**Comment by thewookiewon** [comment]
No prior to restart, sorry if u didn't make that clear

**Comment by b0mbays** [comment]
If it was after changing the global time to end at 01:00 but before restarting then I assume that's the issue.

It should work correctly today if you have the global time not set to 00:00 and you have done a restart since changing the configuration.yaml - changes are only applied via this file after a restart 👍

The integration doesn't handle anything very well when the end/start time is set to 00:00 - I should make it more clear in the documentation.

**Comment by thewookiewon** [comment]
I'm afraid the issue remains

2025-03-24 21:24:47.582 INFO (MainThread) [custom_components.continuously_casting_dashboards.monitoring] Device REDACTED IP (REDACTED IP) is still idle after waiting period, attempting reconnect
2025-03-24 21:24:47.582 INFO (MainThread) [custom_components.continuously_casting_dashboards.monitoring] Outside casting time window for REDACTED IP, skipping reconnect
 Live

**Comment by b0mbays** [comment]
It could be an issue with indentation, could you double check it's like this?

```
logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
switch_entity_id: "input_boolean.ccd_cast"
devices:
  "REDACTED HUB MAX IP": #Required: Display name or IP address of your device. Find this on the actual device's settings or inside the Google Home app.
    - dashboard_url: "http://REDACTED HA IP:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "07:00" #Optional: Set the start time for this device
      end_time: "18:00" #Optional: Set the end time for this device
    - dashboard_url: "http://REDACTED HA IP:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "21:00" #Optional: Set the start time for this device
      end_time: "22:45" #Optional: Set the end time for this device
```

Not sure if it's just the .txt file you sent, but it's incorrect in there.

The volume, start_time and end_time need to be corrected indented.

**Comment by thewookiewon** [comment]
I think that was just the .txt file, looks like putting the code in a desktop web browser rather than mobile respects the formattting

```
logging_level: debug #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
switch_entity_id: "input_boolean.ccd_cast"
devices:
  "192.168.251.86": #Required: Display name or IP address of your device. Find this on the actual device's settings or inside the Google Home app.
    - dashboard_url: "http://192.168.251.77:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "07:00" #Optional: Set the start time for this device
      end_time: "18:00" #Optional: Set the end time for this device
    - dashboard_url: "http://192.168.251.77:8123/givtcp-animated-dashboard/0?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
      volume: 4 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
      start_time: "21:00" #Optional: Set the start time for this device
      end_time: "22:45" #Optional: Set the end time for this device
```
