### ISSUE TITLE
!include_dir_list support for devices?

### ISSUE THREAD

**Issue by jaredcat** [b0mbays/continuously_casting_dashboards#112]
I was trying to do something like this:

```yaml
continuously_casting_dashboards:
  ...
  devices: !include_dir_named continuously_casting_dashboards/
```

and inside `continuously_casting_dashboards` dir:

`living_room_display.yaml`:

```yaml
"Living Room Display":
    - dashboard_url: "<Dashboard_URL>"
      ...
```

But I just couldn't get it to work. Am I doing it wrong, or is this something that needs to be specifically handled by the plugin?
If so, I think that `include_dir_list` and/or `include_dir_named` could really help organize these chunky configs.
