### ISSUE TITLE
logon prompt

### ISSUE THREAD

**Issue by gigaguy** [b0mbays/continuously_casting_dashboards#36]
The integration appears to cast and recast but only makes it to the logon page.  I setup the trusted networks and automations that cast the dashboard work fine (no logon prompt). Any ideas what I could be missing?

Debug log just loops over start/stop, but no errors.

Here is my trusted config
```
homeassistant:
  external_url: "https://ha.test.com"
  packages: !include_dir_named components/packages
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.2  # my Google Nest Hub IP
      trusted_users:
        192.168.1.2: 133b5307165b3328685232
      allow_bypass_login: true
```
