### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by EljaTrum** [b0mbays/continuously_casting_dashboards#42]
I'm getting this error after a recent update to version 1.3.
It stopped casting my dashboard to the Hub too.

```
Logger: homeassistant.setup
Source: setup.py:332
First occurred: 13:31:44 (1 occurrences)
Last logged: 13:31:44

Error during setup of component continuously_casting_dashboards
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/__init__.py", line 20, in async_setup
    caster = ContinuouslyCastingDashboards(hass, conf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/continuously_casting_dashboards/dashboard_caster.py", line 30, in __init__
    device_info.get("start_time", global_start_time), "%H:%M"
    ^^^^^^^^^^^^^^^
AttributeError: 'NodeStrClass' object has no attribute 'get'

```

**Comment by b0mbays** [comment]
Hi @EljaTrum i'm updating to the latest HA release now to see if something in the update broke something. I'll report back! Which HA version are you on?

**Comment by EljaTrum** [comment]
I'm on Core 2023.12.4, Supervisor 2023.12.0, OS 11.2, Frontend 20231208.2.

I tried returning to earlier versions of your integration, but that didn't help (back on v1.3.0 now). 
So it could indeed be something in an HA update.

**Comment by b0mbays** [comment]
@EljaTrum I'm on the same versions as you, and all is working fine... Could you post your config for the integration from your configuration.yaml?

Try and include the formatting too 😊

**Comment by EljaTrum** [comment]
Thanks for looking into this. :)

Here's the part from the configuration:

```
continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 240 #Required: Time (in seconds) for casting checks between each device.
  start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
  end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
  devices:
    "Nesthub": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
        dashboard_url: "https://home.urlredacted.nl:8123/lovelace/nest-hub?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)      
```

**Comment by b0mbays** [comment]
> Thanks for looking into this. :)
> 
> Here's the part from the configuration:
> 
> ```
> continuously_casting_dashboards:
>   logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
>   cast_delay: 240 #Required: Time (in seconds) for casting checks between each device.
>   start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
>   end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
>   devices:
>     "Nesthub": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
>         dashboard_url: "https://home.urlredacted.nl:8123/lovelace/nest-hub?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)      
> ```

Ah I think I see the issue. Can you try the following?

```
 continuously_casting_dashboards:
   logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
   cast_delay: 240 #Required: Time (in seconds) for casting checks between each device.
   start_time: "07:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
   end_time: "01:00" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
   devices:
     "Nesthub": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
       -  dashboard_url: "https://home.urlredacted.nl:8123/lovelace/nest-hub?kiosk" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)      
```

I've added a '-' to the dashboard_url line. Apologies if this wasn't clear in the update notes 😬
