### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Curiosity87** [b0mbays/continuously_casting_dashboards#49]
I have 3 users and we have TOTP activated. 

For whatever reason I can not get it to login automatically on my nest hub. 

I have trusted_proxies as well could that be the problem? Is there anyway around it? Im using a reverse proxy.

Proxies:

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/16
    - 192.168.170.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
```

Auth settings:
```
  external_url: "blablabla.blablabla.vip"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.170.179/32 #IP of my Nesthub
      trusted_users:
        192.168.170.179: 32412dasdasdasdas34asdkhadjkash
      allow_bypass_login: true
    - type: homeassistant
  allowlist_external_dirs:
    - "/config/tmp/"
  auth_mfa_modules:
    - type: totp 
```

Any pointers?
