### ISSUE TITLE
So high cpu usage!

### ISSUE THREAD

**Issue by labaland** [b0mbays/continuously_casting_dashboards#62]
From almost no load to 100 for one Google hub gen2.
Something i have done wrong?

```
continuously_casting_dashboards:
  logging_level: warning #Required: Set the logging level - debug/info/warning (default is 'warning' - try 'debug' for debugging)
  cast_delay: 45 #Required: Time (in seconds) for casting checks between each device.
  start_time: "06:00" #Optional: Global start time of the casting window (format: "HH:MM") - Default is set to "07:00" and can be individually overwritten per device below.
  end_time: "05:59" #Optional: Global end time of the casting window (format: "HH:MM") and must be after "00:00". Default is set to "01:00" and can be individually overwritten per device below.
  devices:
    "Kök": #Required: Display name of your device. Find this on the actual device's settings or inside the Google Home app.
      - dashboard_url: "http://192.168.1.4:8123/g-home/home?kiosk&wp_enabled=true" #Required: Dashboard URL to be casted (This must be the local IP address of your HA instance, not homeassistant.local)
        volume: 5 #Optional: Volume to set the display. (If you remove this, the device will remain the same volume)
#        start_time: "04:31" #Optional: Set the start time for this device
#        end_time: "04:30" #Optional: Set the end time for this device
```

![image](https://github.com/b0mbays/continuously_casting_dashboards/assets/20958435/4d438e92-0555-4178-91dc-766f2b8bf232)
