### ISSUE TITLE
Casting Dashboard with DuckDNS ?

### ISSUE THREAD

**Issue by pb1966** [b0mbays/continuously_casting_dashboards#77]
I use Duckdns to reach Google Nest Hub 2 via Https. 

```
devices: 
"Esszimmer Nest Hub": 
      - dashboard_url: "https://xxxx.duckdns.org:8123/dashboard-test/0" 
```

This can be used to address the dashboard. Local addresses do not work with DuckDNS

The problem is that the trusted_networks and trusted_users do not work because they use local IP addresses. The result is that I am not logged in automatically 

```
auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.xxx.145/32 

      trusted_users:
        192.168.xxx.145/32: panel  

      allow_bypass_login: true
    - type: homeassistant

```

Is there a suggestion for the configuration.yaml in connection with DuckDNS ?
