### ISSUE TITLE
Not able to get IPs from just the Device Name

### ISSUE THREAD

**Issue by Cybercube21** [b0mbays/continuously_casting_dashboards#96]
The Method to get the IPs from the Device name doesn't seem to work reliably with my Google Nest Hubs (2nd gen). It either returns **off** (when just in idle) or **null** if something is already casting on them. 

monitoring.py:45
```
ip = device_manager.async_get_device_ip(device_name)
```

If you change it to take the IPs directly instead of device names like this it works perfectly fine:

monitoring.py:45
```
ip = device_name
```

configuration.yaml
```
continuously_casting_dashboards:
  devices:
    10.X.X.X: 
      - dashboard_url: "http://10.X.X.X:8123/dashboard-default/0"
```
